Fix students and classes screens
JambuOverflow/lepic pull request #109
Opened 2020-12-22 12:02 UTC by FelipOliveira

Attempt to fix screen navigation and injection container

2020-12-22 16:40 UTC, renan-cunha requested changes
The class screen has the fields "id" and "tutor", this tutor field is the primary key of user, and the id is the primary key of the class. That is, these fields must not be on screens, only name and series are needed. The id field you don’t even need to change, can you get the user’s primary key (through the entity / object) to fill in this "tutor" field?

Same thing for student part, no need for id

In addition, if you are in texts, but then you open the menu and press texts again, it shows the home with nothing. I think it should show texts again, right?

And to the add text function, the body part in my opinion is wrong, it's similar to the title. Can't you do something like in other apps, where you type and the text goes down, instead of going to the right indefinitely? It would be interesting to have scroll if the text gets too big

2020-12-22 23:13 UTC, VitorCantao requested changes

2020-12-22 23:16 UTC, VitorCantao commented
Also, why the rename from route_generator to route_generator2?

2020-12-28 19:16 UTC, jvcanavarro approved these changes
![minions](https://user-images.githubusercontent.com/40280586/103237971-0b2dc300-4928-11eb-937d-fa5bdd3c904b.gif)

2020-12-28 19:17 UTC, VitorCantao approved these changes

2020-12-28 19:18 UTC, merged