33 statistics domain
JambuOverflow/lepic pull request #155
Opened 2021-01-27 18:46 UTC by renan-cunha

2021-01-27 22:39 UTC, VitorCantao requested changes

2021-01-27 22:39 UTC, VitorCantao commented on mobile/lib/features/statistics/domain/use_cases/get_number_of_correct_words_read_per_minute_use_case.dart
> +      number_words = text.body.split(" ").length;
I think this should be in the `MyText` entity, probably with a `get`ter

2021-01-27 22:39 UTC, VitorCantao commented on mobile/lib/features/statistics/domain/use_cases/get_number_of_correct_words_read_per_minute_use_case.dart
> +      number_words = text.body.split(" ").length;
`wordCount` and `words`

2021-01-27 22:39 UTC, VitorCantao commented on mobile/lib/features/statistics/domain/use_cases/get_number_of_correct_words_read_per_minute_use_case.dart
> +  Future<Either<Failure, double>> call(AudioParams params) async {
We can probably extract some methods inside this method to make it cleaner and clear

2021-01-27 22:39 UTC, VitorCantao commented on mobile/lib/features/statistics/domain/use_cases/get_number_of_mistaken_words_use_case.dart
> +  Future<Either<Failure, int>> call(CorrectionParams params) async {
Same comment I made in the other one

2021-01-27 22:39 UTC, VitorCantao commented on mobile/test/core/data/text_database_test.dart
> +    test("should return a list with one text", () async {
Commented code should be deleted

2021-01-31 13:09 UTC, renan-cunha commented on mobile/lib/features/statistics/domain/use_cases/get_audio_duration_in_seconds_use_case.dart
> +class GetAudioDurationInMinutesUseCase implements UseCase<int, AudioParams> {
this use isn't finished, and is not returning the actual minutes now. Flutter audio management is different than other frameworks. I will wait for Canavarro to test with an actual audio so I can finish this implementation.

2021-01-31 14:13 UTC, VitorCantao approved these changes

2021-01-31 14:14 UTC, merged