33 statistics presentation
JambuOverflow/lepic pull request #194
Opened 2021-02-27 21:42 UTC by jvcanavarro

2021-02-28 13:59 UTC, VitorCantao requested changes

2021-02-28 13:59 UTC, VitorCantao commented on mobile/test/features/statistics/presentation/bloc/statistic_bloc_test.dart
> +import 'dart:io';
Some tests are missing

2021-02-28 14:09 UTC, VitorCantao commented
@jvcanavarro 
![image](https://user-images.githubusercontent.com/31198065/109421266-5a8a8100-79b5-11eb-8a18-9b94cfe7a7d3.png)

Things like this can still happen

2021-02-28 15:05 UTC, jvcanavarro commented on mobile/lib/features/statistics/domain/entities/statistic.dart
> +import 'package:flutter/foundation.dart';
This class was removed at the last commit

2021-03-01 13:54 UTC, VitorCantao approved these changes

2021-03-01 13:54 UTC, merged