10 crud text local data source
JambuOverflow/lepic pull request #94
Opened 2020-12-17 20:44 UTC by renan-cunha

2020-12-17 21:09 UTC, VitorCantao requested changes

2020-12-17 21:09 UTC, VitorCantao commented on mobile/lib/features/text_management/data/repositories/text_repository_impl.dart
> +  Future<Either<Failure, List<Text>>> getTexts(Classroom classroom) async {
Just a short note:

It's good practice to have your interfaces (public methods) higher in the class, before the private methods

2020-12-17 21:13 UTC, renan-cunha commented on mobile/lib/features/text_management/data/data_sources/text_local_data_source.dart
> +        throw SqliteException(787, "The table doesn't have this entry");
the database function returns, by default, false if the entry is not in the table during deletion. I think it's a matter of taste, what arguments do you have to support your claim?

2020-12-18 15:43 UTC, VitorCantao commented on mobile/lib/features/text_management/data/data_sources/text_local_data_source.dart
> +        throw SqliteException(787, "The table doesn't have this entry");
Abstraction. To make things this way you have to know the internals of the database, but you are not in the database.

2020-12-18 16:19 UTC, VitorCantao approved these changes

2020-12-18 16:19 UTC, merged